const state={workspace:{},workspaces:[],user:null,locked:false,integrations:{},leads:[],conversations:[],appointments:[],invoices:[],automations:[],activities:[],adSpend:[],adFunds:[],billing:{},prospects:[],prospectViews:[],websiteAnalytics:{},websiteUpdates:[],filter:'all',search:'',selectedConversationId:null,selectedLeadId:null,calendarDate:new Date(),rangeDays:30};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:state.workspace.currency||'CAD',maximumFractionDigits:0}).format(Number(n)||0);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=(n='')=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'•';
const relative=iso=>{const d=Math.max(0,(Date.now()-new Date(iso))/1000);if(d<60)return'now';if(d<3600)return`${Math.floor(d/60)}m`;if(d<86400)return`${Math.floor(d/3600)}h`;return`${Math.floor(d/86400)}d`;};
const dateLabel=iso=>new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric'}).format(new Date(iso));
const dateTimeLabel=iso=>new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso));

async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false)throw new Error(data.message||`Request failed (${r.status})`);return data;}
async function bootstrap(){try{const d=await api('/api/app/bootstrap');Object.assign(state,{workspace:d.workspace||{},workspaces:d.workspaces||[],user:d.user||null,locked:!!d.locked,integrations:d.integrations||{},leads:d.leads||[],conversations:d.conversations||[],appointments:d.appointments||[],invoices:d.invoices||[],automations:d.automations||[],activities:d.activities||[],adSpend:d.adSpend||[],adFunds:d.adFunds||[],billing:d.billing||{},prospectViews:d.prospectViews||[],websiteAnalytics:d.websiteAnalytics||{},websiteUpdates:d.websiteUpdates||[]});qs('#authScreen').hidden=true;renderAll();qs('#systemStatus').textContent='Cloud database live';const qp=new URLSearchParams(location.search),sid=qp.get('session_id');if(sid&&(qp.get('billing')==='success'||qp.get('adfund')==='success')){try{await api('/api/app/checkout/confirm?sessionId='+encodeURIComponent(sid));history.replaceState({},'',location.pathname);const d2=await api('/api/app/bootstrap');Object.assign(state,{workspace:d2.workspace||{},workspaces:d2.workspaces||[],user:d2.user||state.user,locked:!!d2.locked,integrations:d2.integrations||{},leads:d2.leads||[],conversations:d2.conversations||[],appointments:d2.appointments||[],invoices:d2.invoices||[],automations:d2.automations||[],activities:d2.activities||[],adSpend:d2.adSpend||[],adFunds:d2.adFunds||[],billing:d2.billing||{},prospectViews:d2.prospectViews||[],websiteAnalytics:d2.websiteAnalytics||{},websiteUpdates:d2.websiteUpdates||[]});renderAll();}catch(err){console.error('Checkout confirmation:',err)}}}catch(e){qs('#authScreen').hidden=false;qs('#systemStatus').textContent=e.message.includes('Supabase')?'Supabase setup required':'Sign in required';if(e.message.includes('Supabase'))qs('#loginStatus').textContent=e.message;console.error(e);}}

function renderSubscriptionGate(){
  const lock=qs('#subscriptionLock');if(!lock)return;
  const locked=state.user?.role!=='owner'&&!!state.locked;
  lock.hidden=!locked;document.body.classList.toggle('subscription-locked',locked);
  const cents=Number(state.billing?.monthlyCents||25000),status=String(state.billing?.status||'inactive');
  if(qs('#lockSubscriptionPrice'))qs('#lockSubscriptionPrice').textContent=money(cents/100);
  if(qs('#lockSubscriptionStatus'))qs('#lockSubscriptionStatus').textContent=status.toUpperCase();
}
function renderAll(){renderSubscriptionGate();renderWorkspace();renderDashboard();renderLeads();renderInbox();renderCalendar();renderPayments();renderAnalytics();renderWebsiteTraffic();renderWebsiteUpdates();renderAutomations();renderSettings();renderNotifications();renderProspects();fillLeadSelects();renderWorkspaceMenu();renderAdmin();}
function renderWorkspace(){const n=state.workspace.businessName||'Your business';qs('#workspaceName').textContent=n;qs('#homeGreeting').textContent=`${n.split(/\s+/)[0]} overview`;qs('.workspace-mark').textContent=(n[0]||'S').toUpperCase();qs('#todayLabel').textContent=new Intl.DateTimeFormat('en-CA',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();const uc=qs('.user-card strong');if(uc&&state.user)uc.textContent=state.user.name;const us=qs('.user-card small');if(us&&state.user)us.textContent=state.user.role==='owner'?'SiteRemade owner':'Administrator';qs('#adminNav').style.display=state.user?.role==='owner'?'grid':'none';}
function greeting(){const h=new Date().getHours();return h<12?'morning':h<18?'afternoon':'evening';}
function inRange(iso){return Date.now()-new Date(iso).getTime()<=state.rangeDays*86400000;}
function renderDashboard(){
  const days=Number(state.rangeDays)||30,ms=days*86400000,nowMs=Date.now();
  const current=state.leads.filter(l=>{const t=new Date(l.createdAt).getTime();return t>=nowMs-ms&&t<=nowMs;});
  const previous=state.leads.filter(l=>{const t=new Date(l.createdAt).getTime();return t>=nowMs-(ms*2)&&t<nowMs-ms;});
  const upcoming=state.appointments.filter(a=>new Date(a.start)>=new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start));
  const won=state.leads.filter(l=>l.status==='Won'),wonValue=won.reduce((sum,l)=>sum+(Number(l.value)||0),0);
  qs('#metricLeads').textContent=current.length;
  const period=qs('#leadMetricPeriod');if(period)period.textContent=`LAST ${days} DAYS`;
  const trend=qs('#leadTrend');if(trend){let label='→ 0%',cls='neutral';if(previous.length===0&&current.length>0){label='↗ NEW';cls='positive';}else if(previous.length>0){const pct=Math.round(((current.length-previous.length)/previous.length)*100);if(pct>0){label=`↗ ${pct}%`;cls='positive';}else if(pct<0){label=`↓ ${Math.abs(pct)}%`;cls='negative';}else label='→ 0%';}trend.textContent=label;trend.className=`trend ${cls}`;}
  qs('#metricAppointments').textContent=upcoming.length;qs('#appointmentMeta').textContent=upcoming.length?`Next: ${upcoming[0].title} · ${dateTimeLabel(upcoming[0].start)}`:'No upcoming appointments';
  const convWithReplies=state.conversations.filter(c=>c.messages?.length>1);qs('#metricResponse').textContent=convWithReplies.length?`${Math.round(convWithReplies.reduce((sum,c)=>{const m=c.messages;return sum+Math.max(1,(new Date(m[1].createdAt)-new Date(m[0].createdAt))/60000)},0)/convWithReplies.length)}m`:'—';
  qs('#metricValue').textContent=money(wonValue);qs('#valueMeta').textContent=`From ${won.length} won opportunit${won.length===1?'y':'ies'}`;qs('#leadBadge').textContent=state.leads.filter(l=>l.status==='New').length;
  renderRecent();renderPipeline();renderActivity();renderBars();
}
function renderRecent(){const list=qs('#recentLeadList');const src=[...state.leads].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);list.innerHTML=src.length?src.map(l=>`<button class="lead-row clickable-lead" data-id="${l.id}"><span class="avatar">${esc(initials(l.name))}</span><div class="lead-person"><strong>${esc(l.name)}</strong><span>${esc(l.phone||l.email||'No contact')}</span></div><span class="lead-service">${esc(l.service)}</span><span class="lead-time">${relative(l.createdAt)}</span><span class="lead-status status-${esc(l.status)}">${esc(l.status)}</span></button>`).join(''):'<div class="empty-state">No leads yet.</div>';qsa('.clickable-lead').forEach(b=>b.onclick=()=>openLead(b.dataset.id));}
function renderActivity(){qs('#activityTimeline').innerHTML=(state.activities||[]).slice(0,6).map(a=>`<div class="timeline-item"><span class="timeline-icon">${({lead:'◎',appointment:'□',payment:'◇',won:'↗',message:'◌',status:'↗',delete:'×'}[a.type]||'•')}</span><div><strong>${esc(a.title)}</strong><p>${esc(a.detail||'')}</p><small>${relative(a.createdAt)}</small></div></div>`).join('')||'<div class="empty-state">Activity will appear here.</div>';}
function renderBars(){const arr=Array.from({length:22},(_,i)=>state.leads.filter(l=>{const age=(Date.now()-new Date(l.createdAt))/86400000;return age>=i&&age<i+1}).length);const max=Math.max(1,...arr);qs('#leadBars').innerHTML=arr.reverse().map(v=>`<i style="height:${20+(v/max)*80}%"></i>`).join('');}
function renderPipeline(){const statuses=['New','Contacted','Quoted','Won','Lost'];const max=Math.max(1,...statuses.map(s=>state.leads.filter(l=>l.status===s).length));qs('#pipelineStats').innerHTML=statuses.map(s=>{const n=state.leads.filter(l=>l.status===s).length;return`<div class="pipeline-column"><span>${s.toUpperCase()}</span><strong>${n}</strong><div class="pipeline-bar"><i style="width:${Math.max(n?8:0,n/max*100)}%"></i></div></div>`}).join('');}

function filteredLeads(){return state.leads.filter(l=>(state.filter==='all'||l.status===state.filter)&&(!state.search||`${l.name} ${l.email} ${l.phone} ${l.service} ${l.source} ${l.message}`.toLowerCase().includes(state.search)));}
function renderLeads(){const leads=filteredLeads();qs('#leadCountLabel').textContent=`${leads.length} lead${leads.length===1?'':'s'}`;qs('#leadTableBody').innerHTML=leads.length?leads.map(l=>`<tr class="lead-table-row" data-id="${l.id}"><td><strong>${esc(l.name)}</strong><small>${esc(l.phone||l.email||'No contact details')}</small></td><td>${esc(l.service)}</td><td>${esc(l.source)}</td><td>${dateLabel(l.createdAt)}</td><td><select class="status-select lead-status status-${esc(l.status)}" data-id="${l.id}">${['New','Contacted','Quoted','Won','Lost'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="row-menu" data-open="${l.id}">•••</button></td></tr>`).join(''):'<tr><td class="empty-row" colspan="6">No leads match this view.</td></tr>';qsa('.status-select').forEach(x=>x.onchange=e=>{e.stopPropagation();updateLead(x.dataset.id,{status:x.value})});qsa('.lead-table-row').forEach(r=>r.onclick=e=>{if(e.target.closest('select,button'))return;openLead(r.dataset.id)});qsa('[data-open]').forEach(b=>b.onclick=()=>openLead(b.dataset.open));}
async function updateLead(id,patch){try{const d=await api(`/api/app/leads/${id}`,{method:'PATCH',body:JSON.stringify(patch)});const i=state.leads.findIndex(x=>x.id===id);if(i>=0)state.leads[i]=d.lead;await refreshLight();if(state.selectedLeadId===id)populateDrawer(d.lead);}catch(e){alert(e.message)}}
function openLead(id){const l=state.leads.find(x=>x.id===id);if(!l)return;state.selectedLeadId=id;populateDrawer(l);qs('#leadDrawer').hidden=false;}
function populateDrawer(l){qs('#drawerName').textContent=l.name;qs('#drawerStatus').value=l.status;qs('#drawerValue').value=l.value||'';qs('#drawerLeadName').value=l.name||'';qs('#drawerService').value=l.service||'';qs('#drawerPhone').value=l.phone||'';qs('#drawerEmail').value=l.email||'';qs('#drawerMessage').value=l.message||'';qs('#drawerNote').value='';qs('#drawerNotes').innerHTML=(l.notes||[]).map(n=>`<div class="note-item">${esc(n)}</div>`).join('')||'<div class="empty-state">No notes yet.</div>';}

function renderInbox(){const list=qs('#conversationList');const unreadTotal=state.conversations.reduce((sum,c)=>sum+Math.max(0,Number(c.unread)||0),0);const badge=qs('#inboxBadge');if(badge){badge.textContent=unreadTotal;badge.style.display=unreadTotal?'grid':'none';}const convs=[...state.conversations].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));if(!state.selectedConversationId&&convs[0])state.selectedConversationId=convs[0].id;list.innerHTML=convs.length?convs.map(c=>{const last=c.messages?.[c.messages.length-1];return`<button class="conversation ${c.id===state.selectedConversationId?'active':''}" data-conv="${c.id}"><span class="avatar small">${initials(c.name)}</span><div><strong>${esc(c.name)}</strong><p>${esc(last?.text||'No messages yet')}</p></div><small>${relative(c.updatedAt)}</small></button>`}).join(''):'<div class="empty-state padded">No conversations yet.</div>';qsa('[data-conv]').forEach(b=>b.onclick=async()=>{state.selectedConversationId=b.dataset.conv;const c=state.conversations.find(x=>x.id===b.dataset.conv);if(c&&c.unread){try{await api(`/api/app/conversations/${c.id}`,{method:'PATCH',body:JSON.stringify({read:true})});c.unread=0;}catch{}}renderInbox();renderNotifications();});renderConversationWindow();}
function renderConversationWindow(){const c=state.conversations.find(x=>x.id===state.selectedConversationId);const input=qs('#messageInput'),send=qs('#messageForm button');if(!c){qs('#conversationName').textContent='Select a conversation';qs('#conversationMode').textContent='No conversation selected';qs('#messageList').innerHTML='<div class="empty-state">Choose a conversation to view messages.</div>';qs('#takeoverButton').disabled=true;input.disabled=true;send.disabled=true;return;}qs('#conversationName').textContent=c.name;qs('#conversationMode').textContent=c.mode==='ai'?'AI is handling this conversation':'You are handling this conversation';qs('#takeoverButton').disabled=false;qs('#takeoverButton').textContent=c.mode==='ai'?'Take over':'Return to AI';input.disabled=false;send.disabled=false;qs('#messageList').innerHTML=(c.messages||[]).map(m=>`<div class="message ${m.from==='customer'?'inbound':m.from==='ai'?'ai':'business'}"><span>${esc(m.text)}</span><small>${relative(m.createdAt)}</small></div>`).join('')||'<div class="empty-state">No messages yet.</div>';qs('#messageList').scrollTop=qs('#messageList').scrollHeight;}

function renderCalendar(){const d=state.calendarDate,y=d.getFullYear(),m=d.getMonth();qs('#calendarTitle').textContent=new Intl.DateTimeFormat('en-CA',{month:'long',year:'numeric'}).format(d);const first=(new Date(y,m,1).getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div class="calendar-day muted-day"></div>';for(let day=1;day<=days;day++){const events=state.appointments.filter(a=>{const x=new Date(a.start);return x.getFullYear()===y&&x.getMonth()===m&&x.getDate()===day}).sort((a,b)=>new Date(a.start)-new Date(b.start));html+=`<div class="calendar-day ${isToday(y,m,day)?'today-cell':''}"><span>${day}</span>${events.map(a=>`<button class="calendar-event" data-appt="${a.id}">${new Intl.DateTimeFormat('en-CA',{hour:'numeric',minute:'2-digit'}).format(new Date(a.start))} · ${esc(a.title)}</button>`).join('')}</div>`}qs('#calendarGrid').innerHTML=html;qsa('[data-appt]').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=state.appointments.find(x=>x.id===b.dataset.appt);if(a&&confirm(`${a.customer||'Customer'} — ${a.title}\n${dateTimeLabel(a.start)}\n\nDelete this appointment?`))deleteAppointment(a.id)});}
function isToday(y,m,d){const n=new Date();return n.getFullYear()===y&&n.getMonth()===m&&n.getDate()===d;}

function renderPayments(){
  const paid=state.invoices.filter(i=>i.status==='Paid'),open=state.invoices.filter(i=>i.status==='Pending');
  const collected=paid.reduce((s,i)=>s+Number(i.amount||0),0),outstanding=open.reduce((s,i)=>s+Number(i.amount||0),0),avg=state.invoices.length?state.invoices.reduce((s,i)=>s+Number(i.amount||0),0)/state.invoices.length:0;
  qs('#payCollected').textContent=money(collected);qs('#payCollectedMeta').textContent=`${paid.length} paid invoice${paid.length===1?'':'s'}`;qs('#payOutstanding').textContent=money(outstanding);qs('#payOutstandingMeta').textContent=`${open.length} open invoice${open.length===1?'':'s'}`;qs('#payAverage').textContent=money(avg);qs('#payConversion').textContent=state.invoices.length?`${Math.round(paid.length/state.invoices.length*100)}%`:'0%';
  qs('#transactionList').innerHTML=state.invoices.length?state.invoices.map(i=>`<div><span class="payment-icon">◇</span><strong>${esc(i.customer)}</strong><span>${esc(i.description)}</span><em>${money(i.amount)}</em><select class="invoice-status ${i.status.toLowerCase()}" data-invoice="${i.id}">${['Draft','Pending','Paid','Void'].map(x=>`<option ${x===i.status?'selected':''}>${x}</option>`).join('')}</select><button class="transaction-delete" data-delete-invoice="${i.id}" title="Delete invoice">×</button></div>`).join(''):'<div class="empty-state">No customer invoices yet.</div>';qsa('[data-invoice]').forEach(sel=>sel.onchange=()=>updateInvoice(sel.dataset.invoice,sel.value));qsa('[data-delete-invoice]').forEach(btn=>btn.onclick=()=>deleteInvoice(btn.dataset.deleteInvoice));
  const monthly=(Number(state.billing?.monthlyCents)||0)/100,status=state.billing?.status||state.workspace.siteRemadeSubscriptionStatus||'inactive';
  qs('#subscriptionPrice').textContent=money(monthly);const ss=qs('#subscriptionStatus');ss.textContent=String(status).replace('_',' ').toUpperCase();ss.classList.toggle('neutral',!['active','trialing'].includes(status));
  qs('#startSubscriptionButton').textContent=['active','trialing'].includes(status)?'Subscription active':'Start monthly plan';qs('#startSubscriptionButton').disabled=['active','trialing'].includes(status);
  const funded=(state.adFunds||[]).filter(f=>f.status==='Funded').reduce((x,f)=>x+Number(f.amount||0),0),spent=(state.adSpend||[]).reduce((x,a)=>x+Number(a.spend||0),0),available=Math.max(0,funded-spent);
  qs('#adFundedTotal').textContent=money(funded);qs('#adFundSpent').textContent=money(spent);qs('#adFundAvailable').textContent=money(available);
  qs('#adFundHistory').innerHTML=(state.adFunds||[]).length?state.adFunds.map(f=>`<div><span class="payment-icon">↗</span><strong>${esc(f.platform)} ads</strong><span>${dateLabel(f.createdAt)}</span><em>${money(f.amount)}</em><span class="status-pill ${f.status==='Funded'?'':'neutral'}">${esc(f.status)}</span></div>`).join(''):'<div class="empty-state">No advertising funds added yet.</div>';const fundForm=qs('#adFundForm');if(fundForm){fundForm.style.display=state.user?.role==='owner'?'none':'grid';if(state.user?.role==='owner')qs('#adFundStatus').textContent='Client approves/funds the advertising budget. You manage campaign delivery and record performance from this workspace.';}
}
function renderAnalytics(){const closed=state.leads.filter(l=>['Won','Lost'].includes(l.status));const won=state.leads.filter(l=>l.status==='Won');const collected=state.invoices.filter(i=>i.status==='Paid').reduce((s,i)=>s+Number(i.amount||0),0);qs('#analyticsLeads').textContent=state.leads.length;qs('#analyticsWinRate').textContent=closed.length?`${Math.round(won.length/closed.length*100)}%`:'0%';qs('#analyticsBookings').textContent=state.appointments.length;qs('#analyticsRevenue').textContent=money(collected);renderAnalyticsBars('#analyticsPipeline',['New','Contacted','Quoted','Won','Lost'].map(k=>[k,state.leads.filter(l=>l.status===k).length]));const src={};state.leads.forEach(l=>src[l.source||'Unknown']=(src[l.source||'Unknown']||0)+1);renderAnalyticsBars('#analyticsSources',Object.entries(src).sort((a,b)=>b[1]-a[1]));renderAdSpend(collected);const form=qs('#adSpendForm');if(form){form.style.display=state.user?.role==='owner'?'grid':'none';const status=qs('#adSpendStatus');if(status&&state.user?.role!=='owner')status.textContent='Campaign spend is managed and reported by SiteRemade.';}}
function renderAnalyticsBars(sel,rows){const max=Math.max(1,...rows.map(r=>r[1]));qs(sel).innerHTML=rows.map(([label,n])=>`<div class="analytics-row"><div><strong>${esc(label)}</strong><span>${n}</span></div><div class="analytics-track"><i style="width:${n/max*100}%"></i></div></div>`).join('')||'<div class="empty-state">No data yet.</div>';}
function renderWebsiteTraffic(){const a=state.websiteAnalytics||{},domain=qs('#trafficDomain'),status=qs('#trafficConnectionStatus');if(domain)domain.value=a.domain||'';if(qs('#trafficSessions'))qs('#trafficSessions').textContent=a.connected?Number(a.sessions||0).toLocaleString('en-CA'):'—';if(qs('#trafficUsers'))qs('#trafficUsers').textContent=a.connected?Number(a.users||0).toLocaleString('en-CA'):'—';if(qs('#trafficPageviews'))qs('#trafficPageviews').textContent=a.connected?Number(a.pageviews||0).toLocaleString('en-CA'):'—';if(qs('#trafficLastSync'))qs('#trafficLastSync').textContent=a.lastSync?dateTimeLabel(a.lastSync):'Not connected';if(status){status.textContent=a.connected?'GOOGLE ANALYTICS CONNECTED':a.domain?'DOMAIN SAVED · ANALYTICS NOT CONNECTED':'ADD WEBSITE DOMAIN';status.classList.toggle('neutral',!a.connected);}}
function renderWebsiteUpdates(){
  const rows=state.websiteUpdates||[],list=qs('#websiteUpdateList'),count=qs('#websiteUpdateCount'),badge=qs('#websiteUpdateBadge');
  const open=rows.filter(r=>r.status!=='Completed').length;
  if(count)count.textContent=`${rows.length} REQUEST${rows.length===1?'':'S'}`;
  if(badge){badge.textContent=open;badge.style.display=open?'grid':'none';}
  if(!list)return;
  list.innerHTML=rows.length?rows.map(r=>`<article class="website-update-item"><div class="website-update-top"><div><span class="website-update-page">${esc(r.page)}</span><strong>${esc(r.request)}</strong></div><span class="status-pill ${r.status==='Completed'?'':'neutral'}">${esc(r.status.toUpperCase())}</span></div><p>${esc(r.notes||'No extra notes.')}</p><div class="website-update-meta"><span>${esc(r.priority)} priority · ${dateTimeLabel(r.createdAt)}</span>${state.user?.role==='owner'?`<select class="website-update-status" data-update-status="${r.id}">${['Requested','In Progress','Completed'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select>`:''}</div></article>`).join(''):'<div class="empty-state">No website update requests yet.</div>';
  qsa('[data-update-status]').forEach(sel=>sel.onchange=()=>updateWebsiteRequest(sel.dataset.updateStatus,sel.value));
}
function renderAutomations(){qs('#automationList').innerHTML=state.automations.map(a=>`<button class="automation-card automation-toggle" data-auto="${a.id}"><span class="automation-icon">${a.id==='lead-confirmation'?'✦':a.id==='lead-alert'?'↗':'□'}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p></div><span class="toggle ${a.enabled?'on':''}"></span></button>`).join('');qsa('[data-auto]').forEach(b=>b.onclick=()=>toggleAutomation(b.dataset.auto));}
function renderSettings(){qs('#settingsBusiness').value=state.workspace.businessName||'';qs('#settingsEmail').value=state.workspace.email||'';qs('#settingsPhone').value=state.workspace.phone||'';qs('#settingsTimezone').value=state.workspace.timezone||'';qs('#aiServices').value=state.workspace.ai?.services||'';qs('#aiServiceArea').value=state.workspace.ai?.serviceArea||'';qs('#aiTone').value=state.workspace.ai?.tone||'';const labels={supabase:'Database + Auth',openai:'AI engine',googlePlaces:'Google Places',resend:'Email',twilio:'SMS',stripe:'Stripe payments'};qs('#integrationList').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="setting-row"><div><strong>${l}</strong><span>${state.integrations[k]?'Connected / configured':'Needs server credentials'}</span></div>${k==='stripe'&&state.integrations.stripe?`<button class="text-button" id="connectStripeButton">${state.workspace.stripeAccountId?'Reconnect':'Connect'}</button>`:`<span class="status-pill ${state.integrations[k]?'':'neutral'}">${state.integrations[k]?'LIVE':'OFF'}</span>`}</div>`).join('');const aiBadge=qs('#aiReceptionistBadge');if(aiBadge){const live=!!state.integrations.openai&&state.workspace.ai?.enabled!==false;aiBadge.textContent=live?'LIVE':'OFF';aiBadge.classList.toggle('neutral',!live);}const sb=qs('#connectStripeButton');if(sb)sb.onclick=async()=>{try{const d=await api('/api/app/integrations/stripe/connect',{method:'POST'});if(d.url)location.href=d.url}catch(e){alert(e.message)}};}
function renderNotifications(){const unread=state.conversations.reduce((s,c)=>s+(c.unread||0),0);qs('#notificationDot').style.display=(unread||state.activities.length)?'block':'none';qs('#notificationList').innerHTML=(state.activities||[]).slice(0,8).map(a=>`<div class="notification-item"><strong>${esc(a.title)}</strong><span>${esc(a.detail||'')}</span><small>${relative(a.createdAt)}</small></div>`).join('')||'<div class="empty-state padded">No activity yet.</div>';}
function fillLeadSelects(){for(const id of ['appointmentLead','invoiceLead','conversationLead']){const el=qs('#'+id);if(!el)continue;const current=el.value;el.innerHTML='<option value="">Choose a lead</option>'+state.leads.map(l=>`<option value="${l.id}">${esc(l.name)} — ${esc(l.service)}</option>`).join('');if(current)el.value=current;}}


function renderProspects(){
  const el=qs('#prospectResults');if(!el)return;
  const purpose=state.prospects[0]?.purpose||qs('#prospectPurpose')?.value||'prospects';
  const labels={prospects:'Sales prospects',commercial:'Commercial targets',partners:'Referral partners',competitors:'Competitors'};
  const title=qs('#prospectResultsTitle');if(title)title.textContent=labels[purpose]||'Businesses';
  qs('#prospectCount').textContent=`${state.prospects.length} FOUND`;
  el.innerHTML=state.prospects.length?state.prospects.map((p,i)=>`<div class="prospect-card ${p.viewed?'prospect-viewed':''} ${p.purpose==='competitors'?'competitor-result':''}"><div><div class="prospect-title-row"><h3>${esc(p.name)}</h3>${p.viewed?'<span class="viewed-badge">VIEWED</span>':''}<span class="prospect-purpose-badge">${esc(labels[p.purpose]||'Business')}</span></div><p>${esc(p.address||'')}</p><p>${esc(p.phone||p.website||'No public contact details')}</p><div class="prospect-meta">${p.rating?`<span>★ ${esc(p.rating)} · ${esc(p.reviews||0)} reviews</span>`:'<span>No rating data</span>'}${p.website?'<span>Website</span>':'<span>No website found</span>'}${p.phone?'<span>Phone available</span>':'<span>No phone found</span>'}</div></div><div class="prospect-actions">${p.website?`<button class="text-button" data-view-prospect="${i}" data-prospect-url="${esc(p.website)}">Open website</button>`:(p.mapsUrl?`<button class="text-button" data-view-prospect="${i}" data-prospect-url="${esc(p.mapsUrl)}">Open Google</button>`:'')}${p.mapsUrl&&p.website?`<button class="text-button" data-view-prospect="${i}" data-prospect-url="${esc(p.mapsUrl)}">Google</button>`:''}${p.purpose==='competitors'?`<button class="secondary-button" data-mark-prospect="${i}">${p.viewed?'Reviewed':'Mark reviewed'}</button>`:`<button class="secondary-button" data-import-prospect="${i}">Add to pipeline</button>`}</div></div>`).join(''):'<div class="empty-state">No businesses matched those filters. Widen the filters or try a different category.</div>';
  qsa('[data-view-prospect]').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.viewProspect),p=state.prospects[i];if(!p)return;window.open(b.dataset.prospectUrl,'_blank','noopener');await markProspectViewed(p);});
  qsa('[data-import-prospect]').forEach(b=>b.onclick=()=>importProspect(Number(b.dataset.importProspect)));
  qsa('[data-mark-prospect]').forEach(b=>b.onclick=async()=>{const p=state.prospects[Number(b.dataset.markProspect)];if(p)await markProspectViewed(p);});
}
async function markProspectViewed(p){if(!p?.placeId||p.viewed)return;try{await api('/api/app/prospects/viewed',{method:'POST',body:JSON.stringify({placeId:p.placeId,name:p.name,website:p.website||''})});p.viewed=true;if(!state.prospectViews.includes(p.placeId))state.prospectViews.push(p.placeId);renderProspects();}catch(e){console.error('Could not save viewed prospect:',e)}}
async function importProspect(i){
  const p=state.prospects[i];if(!p)return;
  try{
    await markProspectViewed(p);
    const source=state.user?.role==='owner'?'SiteRemade':'Market Finder';
    const service=p.purpose==='commercial'?'Commercial prospect':p.purpose==='partners'?'Referral opportunity':'Outbound prospect';
    await api('/api/app/leads',{method:'POST',body:JSON.stringify({name:p.name,phone:p.phone||'',email:'',service,source,message:`${p.address||''}${p.website?` · ${p.website}`:''}${p.rating?` · ${p.rating}★ / ${p.reviews||0} reviews`:''}`})});
    await refreshLight();switchView('leads');
  }catch(e){alert(e.message)}
}
function renderAdSpend(collected=0){
  const rows=state.adSpend||[],spend=rows.reduce((s,r)=>s+Number(r.spend||0),0),leads=rows.reduce((s,r)=>s+Number(r.leads||0),0);
  const spendEl=qs('#adSpendTotal');if(!spendEl)return;
  spendEl.textContent=money(spend);qs('#adLeadTotal').textContent=leads;
  qs('#adCpl').textContent=leads?money(spend/leads):'—';
  qs('#adRoas').textContent=spend?`${(collected/spend).toFixed(1)}×`:'—';
  qs('#adSpendList').innerHTML=rows.length?rows.map(r=>`<div class="ad-spend-row"><div><strong>${esc(r.platform)} · ${esc(r.campaign||'Campaign')}</strong><span>${dateLabel(r.createdAt)} · ${Number(r.leads||0)} leads</span></div><em>${money(r.spend)}</em><span>${r.source==='live'?'LIVE':'MANUAL'}</span></div>`).join(''):'<div class="empty-state">No ad spend recorded yet.</div>';
}
async function askAssistant(prompt){
  const input=qs('#assistantInput'),out=qs('#assistantAnswer'),pill=qs('#assistantStatusPill');
  const text=(prompt||input?.value||'').trim();if(!text)return;
  if(input)input.value='';out.textContent='Thinking…';if(pill)pill.textContent='THINKING';
  try{const d=await api('/api/app/assistant',{method:'POST',body:JSON.stringify({message:text})});out.textContent=d.reply||'No answer returned.';if(pill)pill.textContent=d.ai?'AI':'SMART SUMMARY';}
  catch(e){out.textContent=e.message;if(pill)pill.textContent='ERROR';}
}

async function refreshLight(){const d=await api('/api/app/bootstrap');Object.assign(state,{workspace:d.workspace||{},workspaces:d.workspaces||[],user:d.user||state.user,locked:!!d.locked,integrations:d.integrations||{},leads:d.leads||[],conversations:d.conversations||[],appointments:d.appointments||[],invoices:d.invoices||[],automations:d.automations||[],activities:d.activities||[],adSpend:d.adSpend||[],adFunds:d.adFunds||[],billing:d.billing||{},prospectViews:d.prospectViews||[],websiteAnalytics:d.websiteAnalytics||{},websiteUpdates:d.websiteUpdates||[]});renderAll();}
function switchView(v){qsa('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));qsa('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});if(v==='leads')setTimeout(()=>{},0);}
function showModal(id){qs('#'+id).hidden=false;}function hideModal(id){qs('#'+id).hidden=true;}

qsa('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));qsa('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
qs('#leadFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.filter=b.dataset.status;qsa('#leadFilters button').forEach(x=>x.classList.toggle('active',x===b));renderLeads();};
qs('#leadSearch').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderLeads();};
qs('#globalSearchButton').onclick=()=>{switchView('leads');setTimeout(()=>qs('#leadSearch').focus(),100)};
qs('#notificationButton').onclick=()=>{const p=qs('#notificationPopover');p.hidden=!p.hidden;};qs('#closeNotifications').onclick=()=>qs('#notificationPopover').hidden=true;
qs('#rangeControl').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.rangeDays=Number(b.dataset.days)||30;qsa('#rangeControl button').forEach(x=>x.classList.toggle('active',x===b));renderDashboard();};

['#newLeadButton','#newLeadButton2'].forEach(s=>qs(s).onclick=()=>showModal('leadModal'));qs('#closeLeadModal').onclick=()=>hideModal('leadModal');qs('#cancelLeadModal').onclick=()=>hideModal('leadModal');
qs('#manualLeadForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const out=qs('#manualLeadStatus');out.textContent='Creating…';try{const d=await api('/api/app/leads',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.leads.unshift(d.lead);form.reset();hideModal('leadModal');await refreshLight();switchView('leads');}catch(err){out.textContent=err.message;}};

qs('#closeDrawer').onclick=()=>qs('#leadDrawer').hidden=true;qs('#leadDetailForm').onsubmit=async e=>{e.preventDefault();if(!state.selectedLeadId)return;const fd=Object.fromEntries(new FormData(e.currentTarget));qs('#drawerStatusText').textContent='Saving…';await updateLead(state.selectedLeadId,fd);qs('#drawerStatusText').textContent='Saved.';setTimeout(()=>qs('#drawerStatusText').textContent='',1200)};
qs('#deleteLeadButton').onclick=async()=>{if(!state.selectedLeadId)return;const l=state.leads.find(x=>x.id===state.selectedLeadId);if(!confirm(`Delete ${l?.name||'this lead'}?`))return;try{await api(`/api/app/leads/${state.selectedLeadId}`,{method:'DELETE'});qs('#leadDrawer').hidden=true;state.selectedLeadId=null;await refreshLight();}catch(e){alert(e.message)}};
qs('#messageLeadButton').onclick=async()=>{if(!state.selectedLeadId)return;try{let c=state.conversations.find(x=>x.leadId===state.selectedLeadId);if(!c){const d=await api('/api/app/conversations',{method:'POST',body:JSON.stringify({leadId:state.selectedLeadId})});c=d.conversation;await refreshLight();}state.selectedConversationId=c.id;qs('#leadDrawer').hidden=true;switchView('inbox');renderInbox();}catch(e){alert(e.message)}};
qs('#bookLeadButton').onclick=()=>{if(state.selectedLeadId){showModal('appointmentModal');qs('#appointmentLead').value=state.selectedLeadId;const d=new Date();d.setDate(d.getDate()+1);qs('#appointmentForm [name=date]').value=d.toISOString().slice(0,10);qs('#appointmentForm [name=time]').value='09:00';}};

qs('#newConversationButton').onclick=()=>showModal('conversationModal');qs('#conversationForm').onsubmit=async e=>{e.preventDefault();const leadId=new FormData(e.currentTarget).get('leadId');if(!leadId)return;try{const d=await api('/api/app/conversations',{method:'POST',body:JSON.stringify({leadId})});state.selectedConversationId=d.conversation.id;hideModal('conversationModal');await refreshLight();switchView('inbox');}catch(err){alert(err.message)}};
qs('#messageForm').onsubmit=async e=>{e.preventDefault();const c=state.conversations.find(x=>x.id===state.selectedConversationId),input=qs('#messageInput');if(!c||!input.value.trim())return;const text=input.value.trim();input.value='';try{await api(`/api/app/conversations/${c.id}/messages`,{method:'POST',body:JSON.stringify({text,from:'business'})});await refreshLight();state.selectedConversationId=c.id;renderInbox();}catch(err){alert(err.message)}};
qs('#takeoverButton').onclick=async()=>{const c=state.conversations.find(x=>x.id===state.selectedConversationId);if(!c)return;try{await api(`/api/app/conversations/${c.id}`,{method:'PATCH',body:JSON.stringify({mode:c.mode==='ai'?'human':'ai'})});await refreshLight();state.selectedConversationId=c.id;renderInbox();}catch(e){alert(e.message)}};

qs('#newAppointmentButton').onclick=()=>{showModal('appointmentModal');const d=new Date();d.setDate(d.getDate()+1);qs('#appointmentForm [name=date]').value=d.toISOString().slice(0,10);qs('#appointmentForm [name=time]').value='09:00';};
qs('#appointmentForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));const lead=state.leads.find(l=>l.id===f.leadId);f.customer=lead?.name||'';f.start=new Date(`${f.date}T${f.time}:00`).toISOString();try{await api('/api/app/appointments',{method:'POST',body:JSON.stringify(f)});form.reset();hideModal('appointmentModal');await refreshLight();switchView('calendar');}catch(err){qs('#appointmentStatus').textContent=err.message}};
async function deleteAppointment(id){try{await api(`/api/app/appointments/${id}`,{method:'DELETE'});await refreshLight();}catch(e){alert(e.message)}}
qs('#prevMonthButton').onclick=()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()-1,1);renderCalendar()};qs('#nextMonthButton').onclick=()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()+1,1);renderCalendar()};qs('#todayButton').onclick=()=>{state.calendarDate=new Date();renderCalendar()};

qs('#newInvoiceButton').onclick=()=>showModal('invoiceModal');qs('#invoiceForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));const lead=state.leads.find(l=>l.id===f.leadId);f.customer=lead?.name||'';try{await api('/api/app/invoices',{method:'POST',body:JSON.stringify(f)});form.reset();hideModal('invoiceModal');await refreshLight();switchView('payments');}catch(err){qs('#invoiceStatus').textContent=err.message}};
async function updateInvoice(id,status){try{await api(`/api/app/invoices/${id}`,{method:'PATCH',body:JSON.stringify({status})});await refreshLight();}catch(e){alert(e.message)}}
async function deleteInvoice(id){
  const inv=state.invoices.find(x=>x.id===id);if(!inv)return;
  if(!confirm(`Delete ${inv.customer}'s ${inv.description} invoice?\n\nThis removes the record from SiteRemade. It does not refund or cancel a payment already processed by Stripe.`))return;
  try{
    const result=await api(`/api/app/invoices/${id}`,{method:'DELETE'});
    if(!result?.ok)throw new Error(result?.message||'Could not delete invoice.');
    state.invoices=state.invoices.filter(x=>x.id!==id);
    renderPayments();renderDashboard();renderAnalytics();fillLeadSelects();
    await refreshLight();
  }catch(e){alert(e.message)}
}
async function updateWebsiteRequest(id,status){try{await api(`/api/app/website-updates/${id}`,{method:'PATCH',body:JSON.stringify({status})});await refreshLight();}catch(e){alert(e.message)}}
if(qs('#lockStartSubscriptionButton'))qs('#lockStartSubscriptionButton').onclick=async()=>{const out=qs('#lockBillingStatus');out.textContent='Opening secure billing…';try{const d=await api('/api/app/billing/subscription/start',{method:'POST'});if(d.url)location.href=d.url}catch(e){out.textContent=e.message}};
if(qs('#lockManageBillingButton'))qs('#lockManageBillingButton').onclick=async()=>{const out=qs('#lockBillingStatus');out.textContent='Opening billing portal…';try{const d=await api('/api/app/billing/portal',{method:'POST'});if(d.url)location.href=d.url}catch(e){out.textContent=e.message}};
if(qs('#lockLogoutButton'))qs('#lockLogoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch{}location.reload()};
if(qs('#startSubscriptionButton'))qs('#startSubscriptionButton').onclick=async()=>{const out=qs('#billingStatus');out.textContent='Opening secure billing…';try{const d=await api('/api/app/billing/subscription/start',{method:'POST'});if(d.url)location.href=d.url}catch(e){out.textContent=e.message}};
if(qs('#manageBillingButton'))qs('#manageBillingButton').onclick=async()=>{const out=qs('#billingStatus');out.textContent='Opening billing portal…';try{const d=await api('/api/app/billing/portal',{method:'POST'});if(d.url)location.href=d.url}catch(e){out.textContent=e.message}};
if(qs('#adFundForm'))qs('#adFundForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,out=qs('#adFundStatus');out.textContent='Opening secure checkout…';try{const d=await api('/api/app/ad-funds',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(d.url)location.href=d.url}catch(err){out.textContent=err.message}};

async function toggleAutomation(id){const a=state.automations.find(x=>x.id===id);if(!a)return;try{await api(`/api/app/automations/${id}`,{method:'PATCH',body:JSON.stringify({enabled:!a.enabled})});await refreshLight();}catch(e){alert(e.message)}}
qs('#settingsForm').onsubmit=async e=>{e.preventDefault();const out=qs('#settingsStatus');out.textContent='Saving…';try{const d=await api('/api/app/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});state.workspace=d.workspace;renderAll();out.textContent='Saved.';setTimeout(()=>out.textContent='',1500)}catch(err){out.textContent=err.message}};

qsa('[data-close]').forEach(b=>b.onclick=()=>hideModal(b.dataset.close));qsa('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){qsa('.modal-backdrop').forEach(m=>m.hidden=true);qs('#leadDrawer').hidden=true;qs('#notificationPopover').hidden=true;}});


function renderWorkspaceMenu(){const menu=qs('#workspaceMenu');if(!menu)return;menu.innerHTML=(state.workspaces||[]).map(w=>`<button data-workspace="${w.id}" class="workspace-option ${w.id===state.workspace.id?'active':''}"><span>${esc(w.businessName)}</span><small>${esc(w.plan||'Client')}</small></button>`).join('');qsa('[data-workspace]').forEach(b=>b.onclick=async()=>{await api('/api/app/workspaces/switch',{method:'POST',body:JSON.stringify({workspaceId:b.dataset.workspace})});menu.hidden=true;await refreshLight();});}
async function renderAdmin(){if(state.user?.role!=='owner')return;try{const d=await api('/api/app/admin');qs('#adminWorkspaceList').innerHTML=d.workspaces.map(w=>`<div class="admin-row growth-admin-row"><div><strong>${esc(w.businessName)}</strong><span>${esc(w.email||'No email')} · ${Number(w.leads||0)} leads · ${money(w.adFunded||0)} funded · ${money(w.adSpent||0)} spent</span></div><div class="admin-actions"><span class="status-pill ${['active','trialing'].includes(w.siteRemadeSubscriptionStatus)?'':'neutral'}">${esc((w.siteRemadeSubscriptionStatus||'inactive').toUpperCase())}</span><button class="secondary-button" data-open-workspace="${w.id}">Open workspace</button></div></div>`).join('');qs('#adminWorkspaceSelect').innerHTML=d.workspaces.map(w=>`<option value="${w.id}">${esc(w.businessName)}</option>`).join('');qsa('[data-open-workspace]').forEach(b=>b.onclick=async()=>{await api('/api/app/workspaces/switch',{method:'POST',body:JSON.stringify({workspaceId:b.dataset.openWorkspace})});await refreshLight();switchView('home');});}catch{}}
qs('#loginForm').onsubmit=async e=>{e.preventDefault();const out=qs('#loginStatus');out.textContent='Signing in…';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});out.textContent='';await bootstrap();}catch(err){out.textContent=err.message}};
function setAuthMode(mode){const login=qs('#loginForm'),signup=qs('#signupForm'),a=qs('#showLogin'),b=qs('#showSignup');const isSignup=mode==='signup';login.hidden=isSignup;signup.hidden=!isSignup;a.classList.toggle('active',!isSignup);b.classList.toggle('active',isSignup);a.setAttribute('aria-selected',String(!isSignup));b.setAttribute('aria-selected',String(isSignup));}
qs('#showLogin').onclick=()=>setAuthMode('login');
qs('#showSignup').onclick=()=>setAuthMode('signup');
qs('#signupForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,out=qs('#signupStatus');out.className='';out.textContent='Creating your workspace…';try{const d=await api('/api/auth/signup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});out.className='success';out.textContent='Account created. Loading your workspace…';await bootstrap();}catch(err){out.className='error';out.textContent=err.message;}};
qs('#logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch{}location.reload()};
qs('#workspaceSwitchButton').onclick=()=>{const m=qs('#workspaceMenu');m.hidden=!m.hidden};
qs('#aiSettingsForm').onsubmit=async e=>{e.preventDefault();await api('/api/app/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await refreshLight();};
if(qs('#testAiButton'))qs('#testAiButton').onclick=()=>{const demo=qs('#widgetDemo');demo.hidden=false;const msgs=qs('#widgetMessages');msgs.innerHTML='<div class="widget-bubble ai">Hi — tell me what you need help with and I’ll get the details for the business.</div>';};
if(qs('#closeWidgetDemo'))qs('#closeWidgetDemo').onclick=()=>qs('#widgetDemo').hidden=true;
if(qs('#widgetForm'))qs('#widgetForm').onsubmit=async e=>{e.preventDefault();const text=qs('#widgetText').value.trim();if(!text)return;const msgs=qs('#widgetMessages');const safe=esc(text);msgs.insertAdjacentHTML('beforeend',`<div class="widget-bubble customer">${safe}</div>`);qs('#widgetText').value='';try{const d=await api('/api/public/chat',{method:'POST',body:JSON.stringify({workspaceId:state.workspace.id,publicKey:state.workspace.publicKey,leadId:qs('#widgetForm').dataset.leadId||'',name:qs('#widgetName').value.trim(),email:qs('#widgetEmail').value.trim(),phone:qs('#widgetPhone').value.trim(),text})});qs('#widgetForm').dataset.leadId=d.leadId||'';msgs.insertAdjacentHTML('beforeend',`<div class="widget-bubble ai">${esc(d.reply)}</div>`);}catch(err){msgs.insertAdjacentHTML('beforeend',`<div class="widget-bubble ai">${esc(err.message)}</div>`);}msgs.scrollTop=msgs.scrollHeight;};
qs('#workspaceForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const out=qs('#workspaceFormStatus');try{await api('/api/app/workspaces',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();out.textContent='Workspace created.';await refreshLight();}catch(err){out.textContent=err.message}};
qs('#userForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const out=qs('#userFormStatus');try{await api('/api/app/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();out.textContent='User created.';await renderAdmin();}catch(err){out.textContent=err.message}};

if(qs('#websiteUpdateForm'))qs('#websiteUpdateForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,out=qs('#websiteUpdateStatus');out.textContent='Sending…';try{await api('/api/app/website-updates',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();out.textContent='Request sent to SiteRemade.';await refreshLight();switchView('website-updates');}catch(err){out.textContent=err.message;}};
if(qs('#assistantForm'))qs('#assistantForm').onsubmit=e=>{e.preventDefault();askAssistant();};
qsa('[data-assistant-prompt]').forEach(b=>b.onclick=()=>askAssistant(b.dataset.assistantPrompt));
if(qs('#askAdsButton'))qs('#askAdsButton').onclick=()=>{switchView('home');setTimeout(()=>askAssistant('Analyze my ad spend, leads and collected revenue. Tell me what looks good, what looks weak, and what I should do next.'),100)};
if(qs('#websiteTrafficForm'))qs('#websiteTrafficForm').onsubmit=async e=>{e.preventDefault();const out=qs('#websiteTrafficStatus');out.textContent='Saving…';try{const d=await api('/api/app/analytics/website',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});state.websiteAnalytics=d.websiteAnalytics||{};renderWebsiteTraffic();out.textContent='Website domain saved. Connect Google Analytics to show real visitor traffic.';}catch(err){out.textContent=err.message;}};
if(qs('#prospectingForm'))qs('#prospectingForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,out=qs('#prospectingStatus');out.textContent='Searching Google Places…';try{const d=await api('/api/app/prospects/search',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.prospects=d.prospects||[];out.textContent=d.live?`${state.prospects.length} businesses matched your search and filters.`:'Market Finder needs a Google Places API key.';renderProspects();}catch(err){out.textContent=err.message;}};
if(qs('#adSpendForm'))qs('#adSpendForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,out=qs('#adSpendStatus');out.textContent='Saving…';try{await api('/api/app/ad-spend',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();out.textContent='Saved.';await refreshLight();}catch(err){out.textContent=err.message;}};

if('serviceWorker' in navigator){
  navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister()))).finally(()=>{
    navigator.serviceWorker.register('/sw.js?v=14').catch(()=>{});
  });
}

bootstrap();
